name: "Test 1"
on:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        #nix_path: nixpkgs=channel:nixos-unstable
        nix_install_url : https://releases.nixos.org/nix/nix-2.19.1/install
    - name : Python test
      run: python3 -m pip install Django
    - run: pip install ipython
    - run: nix-shell --run 'make test-ci' --show-trace
