name: "Test 1"
on:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name : Python test
      run: |
            python3 -m pip install Django
            apt install software-properties-common && add-apt-repository ppa:deadsnakes/ppa && apt update && apt install python3.7
            update-alternatives --install /usr/bin/python python /usr/bin/python3.7*
    - run: nix-shell --run 'make test-ci' --show-trace
