name: "Test 1"
on:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name : Python test
      run: |
            python3 -m pip install Django
            sudo apt install software-properties-common && sudo add-apt-repository ppa:deadsnakes/ppa && sudo apt update && sudo apt install python3.7
            ls /usr/bin/python*
            sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 1 && sudo update-alternatives --config python3
            python3 --version
            pip install pytest
            pip install setuptools
            sudo apt install python3.7-distutils
            PYTHONPATH=. pytest
    - run: nix-shell --run 'make test-ci' --show-trace
