name: "Test 1"
on:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v26
    - name : Python test
      run: |
            python3 -m pip install Django
            pip uninstall ipython
    - run: nix-shell --run 'make test-ci' --show-trace
